import { Geist, Geist_Mono } from "next/font/google";
import "../public/css/globals.css";
import "../public/css/HeroStyle.css";
import Navbar from "./pages/Navbar"; // Adjust path
import Heropage from "./pages/Heropage";
import Aboutpage from "./pages/Aboutpage";
import Profession from "./pages/Profession";
import ProjectsPage from "./pages/Projects";
import Contactpage from "./pages/Contactpage";
import Footer from "./pages/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jovino Monterde",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="main-wrapper">
          <div className="navbar-wrapper sticky top-0 left-0 w-full h-full"><Navbar /></div>
          <main className="w-full h-full">
            <section id="hero" className="hero-wrapper w-full h-auto lg:pt-[200px] md:pt-[200px] pt-[90px] pb-[30] relative bg-slate-50">
              <Heropage />
            </section>
            <section id="aboutpage" className="w-full h-auto lg:py-[200px] md:py-[150px] px-4 overflow-hidden bg-slate-50">
              <Aboutpage />
            </section>
            <section id="profession" className="w-full h-auto p-4 lg:py-[200px] md:py-[150px] py-[100px] bg-[#1692a1]">
              <Profession />
            </section>
            <section id="projects" className="projects-wrapper w-full h-auto pb-10 lg:pt-[200px] md:pt-[150px] pt-[100px] bg-slate-200">
              <ProjectsPage />
            </section>
            <section id="Contact" className="w-full h-auto lg:py-[200px] md:py-[150px] py-[100px] px-4 bg-slate-50">
              <Contactpage />
            </section>
            <section className="w-full h-auto">
              <Footer />
            </section>
            
            {/* {children} */}
          </main>
        </div>
      </body>
    </html>
  );
}
